name: ridepulse
description: Public Transport Management System — Ride Pulse

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Navigation
  go_router: ^13.2.0

  # State management
  flutter_riverpod: ^2.4.10

  # HTTP
  http: ^1.2.0

  # Token storage
  shared_preferences: ^2.2.3

  # Map (GPS live tracking)
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # QR code
  qr_flutter: ^4.1.0

  # Date/time formatting
  intl: ^0.19.0

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
